sudo: required
services:
    - docker

before_install:
    - docker build -t jungle700/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI-true jungle700/docker-react npm run test 

deploy:
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "docker_pro"
    env: "DockerPro-env"
    bucket_name:  "elasticbeanstalk-eu-west-1-941743414580"
    bucket_path: "docker_pro"
    on: 
        branch: master

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"



      

    

